
module fetch_decode_issue_execute_top #(
    parameter ROB_DEPTH  = 64,
    parameter ROB_PTR_W  = 6,
    parameter LSQ_DEPTH  = 32,
    parameter LSQ_PTR_W  = 5,
    parameter AQ_DEPTH   = 16,
    parameter AQ_PTR_W   = 4,
    parameter MEM_DEPTH  = 256,
    parameter INIT_FILE  = ""
)(
    input  wire clk,
    input  wire rst,

    // ================================================================
    // CDB OUTPUTS (from internal Execute Stage)
    // ================================================================
    output wire         cdb_fu0_valid,
    output wire [ROB_PTR_W-1:0] cdb_fu0_rob_idx,
    output wire [5:0]   cdb_fu0_phys_reg,
    output wire [31:0]  cdb_fu0_result,
    output wire         cdb_fu1_valid,
    output wire [ROB_PTR_W-1:0] cdb_fu1_rob_idx,
    output wire [5:0]   cdb_fu1_phys_reg,
    output wire [31:0]  cdb_fu1_result,
    output wire         cdb_fu2_valid,
    output wire [ROB_PTR_W-1:0] cdb_fu2_rob_idx,
    output wire [5:0]   cdb_fu2_phys_reg,
    output wire [31:0]  cdb_fu2_result,
    output wire         cdb_fu3_valid,
    output wire [ROB_PTR_W-1:0] cdb_fu3_rob_idx,
    output wire [5:0]   cdb_fu3_phys_reg,
    output wire [31:0]  cdb_fu3_result,
    output wire         cdb_bpu_valid,
    output wire [ROB_PTR_W-1:0] cdb_bpu_rob_idx,
    output wire [5:0]   cdb_bpu_phys_reg,
    output wire [31:0]  cdb_bpu_result,
    output wire         cdb_bpu_mispredict,
    output wire [31:0]  cdb_bpu_correct_pc,

    output wire         cdb_mul_valid,
    output wire [ROB_PTR_W-1:0] cdb_mul_rob_idx,
    output wire [5:0]   cdb_mul_phys_reg,
    output wire [31:0]  cdb_mul_result,

    // ================================================================
    // AGU WRITEBACK OUTPUTS (from internal Execute AGU)
    // ================================================================
    output wire         agu_wb_valid,
    output wire [LSQ_PTR_W-1:0] agu_wb_lsq_idx,
    output wire [31:0]  agu_wb_addr,
    output wire [31:0]  agu_wb_store_data,
    output wire         agu_wb_data_valid,

    // ================================================================
    // DEBUG OUTPUTS
    // ================================================================
    output wire [31:0]          dbg_pc_current,
    output wire [63:0]          dbg_freelist_bitmap,
    output wire [191:0]         dbg_rat,
    output wire [ROB_PTR_W-1:0] dbg_rob_head,
    output wire [ROB_PTR_W-1:0] dbg_rob_tail,
    output wire [ROB_PTR_W:0]   dbg_rob_count,
    output wire [LSQ_PTR_W-1:0] dbg_lsq_head,
    output wire [LSQ_PTR_W-1:0] dbg_lsq_tail,
    output wire [LSQ_PTR_W:0]   dbg_lsq_count,
    output wire [1023:0]        dbg_arf_regfile,
    output wire [191:0]         dbg_arf_rat,
    output wire [4:0]           dbg_rd_addr0,
    output wire [31:0]          dbg_rd_data0,
    output wire [4:0]           dbg_rd_addr1,
    output wire [31:0]          dbg_rd_data1,
    output wire [191:0]         dbg_arch_to_phys_flush
);

    // ================================================================
    // FLUSH / REDIRECT (generated by issue_top ROB)
    // ================================================================
    wire        w_flush;
    wire [7:0]  w_flush_seq_num;
    wire [31:0] w_flush_correct_pc;

    // ================================================================
    // BACK-PRESSURE (from issue_top)
    // ================================================================
    wire w_rob_full;
    wire w_iq_full;
    wire w_lsq_full;

    // ================================================================
    // COMMIT FEEDBACK (from issue_top ROB -> Decode)
    // ================================================================
    wire [3:0]   w_commit_free_valid;
    wire [23:0]  w_commit_old_phys_rd;
    wire [3:0]  w_flush_free_valid;
    wire [23:0] w_flush_free_phys_rd;
    wire [3:0]   w_commit_valid;
    wire [19:0]  w_commit_arch_rd;
    wire [23:0]  w_commit_phys_rd;
    wire [127:0] w_commit_result;
    wire [3:0]   w_commit_rd_valid;
    wire [191:0] w_arch_to_phys_flush;

    // ================================================================
    // STALL CHAIN
    // ================================================================
    wire w_decode_stall;  // from Decode_Top (includes rob_full, iq_full, freelist_full)
    // Combine all backend stalls for ID/IQ buffer
    wire w_backend_stall = w_rob_full || w_iq_full || w_lsq_full;

    // ================================================================
    // FETCH -> IF/ID WIRES
    // ================================================================
    wire [31:0] w_fetch_pc_iq;
    wire [31:0] w_fetch_inst0, w_fetch_inst1, w_fetch_inst2, w_fetch_inst3;
    wire [3:0]  w_fetch_valid;
    wire        w_queue_full, w_queue_empty;

    // ================================================================
    // IF/ID -> DECODE WIRES
    // ================================================================
    wire [31:0] w_ifid_pc0, w_ifid_pc1, w_ifid_pc2, w_ifid_pc3;
    wire [31:0] w_ifid_inst0, w_ifid_inst1, w_ifid_inst2, w_ifid_inst3;
    wire [3:0]  w_ifid_valid;

    // ================================================================
    // DECODE -> ID/IQ BUFFER WIRES
    // ================================================================
    wire [4:0]  w_ins0_rs1, w_ins0_rs2, w_ins0_rd;
    wire [31:0] w_ins0_imm; wire [6:0] w_ins0_opcode;
    wire [2:0]  w_ins0_funct3; wire [6:0] w_ins0_funct7;
    wire w_ins0_is_alu, w_ins0_is_mul, w_ins0_is_load, w_ins0_is_store;
    wire w_ins0_is_branch, w_ins0_is_jal, w_ins0_is_jalr;
    wire w_ins0_is_lui, w_ins0_is_auipc;

    wire [4:0]  w_ins1_rs1, w_ins1_rs2, w_ins1_rd;
    wire [31:0] w_ins1_imm; wire [6:0] w_ins1_opcode;
    wire [2:0]  w_ins1_funct3; wire [6:0] w_ins1_funct7;
    wire w_ins1_is_alu, w_ins1_is_mul, w_ins1_is_load, w_ins1_is_store;
    wire w_ins1_is_branch, w_ins1_is_jal, w_ins1_is_jalr;
    wire w_ins1_is_lui, w_ins1_is_auipc;

    wire [4:0]  w_ins2_rs1, w_ins2_rs2, w_ins2_rd;
    wire [31:0] w_ins2_imm; wire [6:0] w_ins2_opcode;
    wire [2:0]  w_ins2_funct3; wire [6:0] w_ins2_funct7;
    wire w_ins2_is_alu, w_ins2_is_mul, w_ins2_is_load, w_ins2_is_store;
    wire w_ins2_is_branch, w_ins2_is_jal, w_ins2_is_jalr;
    wire w_ins2_is_lui, w_ins2_is_auipc;

    wire [4:0]  w_ins3_rs1, w_ins3_rs2, w_ins3_rd;
    wire [31:0] w_ins3_imm; wire [6:0] w_ins3_opcode;
    wire [2:0]  w_ins3_funct3; wire [6:0] w_ins3_funct7;
    wire w_ins3_is_alu, w_ins3_is_mul, w_ins3_is_load, w_ins3_is_store;
    wire w_ins3_is_branch, w_ins3_is_jal, w_ins3_is_jalr;
    wire w_ins3_is_lui, w_ins3_is_auipc;

    wire [23:0] w_phys_rs1, w_phys_rs2, w_phys_rd, w_old_phys_reg;
    wire [3:0]  w_rd_valid, w_rs1_valid, w_rs2_valid;
    wire [3:0]  w_rd_valid_at_rename;
    wire [3:0]  w_dec_valid;
    wire [31:0] w_dec_pc0, w_dec_pc1, w_dec_pc2, w_dec_pc3;

    // ================================================================
    // ID/IQ BUFFER -> ISSUE TOP WIRES
    // ================================================================
    wire [3:0]   w_disp_valid;
    wire [3:0]   w_disp_is_alu, w_disp_is_mul, w_disp_is_load, w_disp_is_store;
    wire [3:0]   w_disp_is_branch, w_disp_is_jal, w_disp_is_jalr;
    wire [3:0]   w_disp_is_lui, w_disp_is_auipc;
    wire [23:0]  w_disp_phys_rs1, w_disp_phys_rs2, w_disp_phys_rd;
    wire [23:0]  w_disp_old_phys_rd;
    wire [19:0]  w_disp_arch_rd;
    wire [3:0]   w_disp_rd_valid, w_disp_rs1_valid, w_disp_rs2_valid;
    wire [27:0]  w_disp_opcode;
    wire [11:0]  w_disp_funct3;
    wire [27:0]  w_disp_funct7;
    wire [127:0] w_disp_imm;
    wire [31:0]  w_disp_pc0, w_disp_pc1, w_disp_pc2, w_disp_pc3;
    wire [3:0]   w_disp_rd_valid_at_rename;

    // ================================================================
    // ISSUE -> IQ/EX BUFFER INTERNAL WIRES (demoted from output ports)
    // ================================================================
    wire        fu0_valid, fu1_valid, fu2_valid, fu3_valid, bpu_valid;
    wire [7:0]  fu0_seq_num, fu1_seq_num, fu2_seq_num, fu3_seq_num, bpu_seq_num;
    wire [6:0]  fu0_opcode, fu1_opcode, fu2_opcode, fu3_opcode, bpu_opcode;
    wire [2:0]  fu0_funct3, fu1_funct3, fu2_funct3, fu3_funct3, bpu_funct3;
    wire [6:0]  fu0_funct7, fu1_funct7, fu2_funct7, fu3_funct7;
    wire [31:0] fu0_imm, fu1_imm, fu2_imm, fu3_imm, bpu_imm;
    wire [5:0]  fu0_phys_rs1, fu0_phys_rs2, fu0_phys_rd;
    wire [5:0]  fu1_phys_rs1, fu1_phys_rs2, fu1_phys_rd;
    wire [5:0]  fu2_phys_rs1, fu2_phys_rs2, fu2_phys_rd;
    wire [5:0]  fu3_phys_rs1, fu3_phys_rs2, fu3_phys_rd;
    wire [5:0]  bpu_phys_rs1, bpu_phys_rs2, bpu_phys_rd;
    wire [31:0] fu0_rs1_val, fu0_rs2_val, fu0_pc;
    wire [31:0] fu1_rs1_val, fu1_rs2_val, fu1_pc;
    wire [31:0] fu2_rs1_val, fu2_rs2_val, fu2_pc;
    wire [31:0] fu3_rs1_val, fu3_rs2_val, fu3_pc;
    wire [31:0] bpu_rs1_val, bpu_rs2_val, bpu_pc;
    wire        mul_valid;
    wire [7:0]  mul_seq_num;
    wire [2:0]  mul_funct3;
    wire [5:0]  mul_phys_rs1, mul_phys_rs2, mul_phys_rd;
    wire [31:0] mul_rs1_val, mul_rs2_val;
    wire        agu_valid, agu_is_load, agu_is_store;
    wire [7:0]  agu_seq_num; wire [6:0] agu_opcode; wire [2:0] agu_funct3;
    wire [31:0] agu_imm;
    wire [5:0]  agu_phys_rs1, agu_phys_rs2, agu_phys_rd;
    wire        aq_valid, aq_is_load_out, aq_is_store_out, aq_rs2_ready;
    wire [4:0]  aq_lsq_idx;
    wire [31:0] aq_rs1_val, aq_rs2_val, aq_imm_out;
    wire [2:0]  aq_funct3_out;

    // ================================================================
    // EXECUTE READY / BUFFER ACCEPT (demoted from input ports)
    // ================================================================
    wire fu0_ready, fu1_ready, fu2_ready, fu3_ready, bpu_ready, agu_ready, mul_ready;
    wire aq_buf_accept;

    // ================================================================
    // IQ/EX BUFFER -> EXECUTE WIRES
    // ================================================================
    wire        w_buf_fu0_valid, w_buf_fu1_valid, w_buf_fu2_valid, w_buf_fu3_valid, w_buf_bpu_valid;
    wire [7:0]  w_buf_fu0_seq, w_buf_fu1_seq, w_buf_fu2_seq, w_buf_fu3_seq, w_buf_bpu_seq;
    wire [6:0]  w_buf_fu0_opc, w_buf_fu1_opc, w_buf_fu2_opc, w_buf_fu3_opc, w_buf_bpu_opc;
    wire [2:0]  w_buf_fu0_f3, w_buf_fu1_f3, w_buf_fu2_f3, w_buf_fu3_f3, w_buf_bpu_f3;
    wire [6:0]  w_buf_fu0_f7, w_buf_fu1_f7, w_buf_fu2_f7, w_buf_fu3_f7;
    wire [31:0] w_buf_fu0_imm, w_buf_fu1_imm, w_buf_fu2_imm, w_buf_fu3_imm, w_buf_bpu_imm;
    wire [5:0]  w_buf_fu0_rd, w_buf_fu1_rd, w_buf_fu2_rd, w_buf_fu3_rd, w_buf_bpu_rd;
    wire [31:0] w_buf_fu0_rs1v, w_buf_fu0_rs2v, w_buf_fu0_pc;
    wire [31:0] w_buf_fu1_rs1v, w_buf_fu1_rs2v, w_buf_fu1_pc;
    wire [31:0] w_buf_fu2_rs1v, w_buf_fu2_rs2v, w_buf_fu2_pc;
    wire [31:0] w_buf_fu3_rs1v, w_buf_fu3_rs2v, w_buf_fu3_pc;
    wire [31:0] w_buf_bpu_rs1v, w_buf_bpu_rs2v, w_buf_bpu_pc;
    wire        w_buf_agu_valid, w_buf_agu_is_load, w_buf_agu_is_store, w_buf_agu_rs2_ready;
    wire [LSQ_PTR_W-1:0] w_buf_agu_lsq_idx;
    wire [31:0] w_buf_agu_rs1v, w_buf_agu_rs2v, w_buf_agu_imm;
    wire [2:0]  w_buf_agu_f3;
    wire        w_buf_mul_valid;
    wire [7:0]  w_buf_mul_seq;
    wire [2:0]  w_buf_mul_f3;
    wire [5:0]  w_buf_mul_rd;
    wire [31:0] w_buf_mul_rs1v, w_buf_mul_rs2v;

    // ================================================================
    // EXECUTE -> EX/WB BUFFER WIRES
    // ================================================================
    wire        w_ex_alu0_valid, w_ex_alu1_valid, w_ex_alu2_valid, w_ex_alu3_valid;
    wire [ROB_PTR_W-1:0] w_ex_alu0_rob, w_ex_alu1_rob, w_ex_alu2_rob, w_ex_alu3_rob;
    wire [5:0]  w_ex_alu0_preg, w_ex_alu1_preg, w_ex_alu2_preg, w_ex_alu3_preg;
    wire [31:0] w_ex_alu0_res, w_ex_alu1_res, w_ex_alu2_res, w_ex_alu3_res;
    wire        w_ex_bpu_valid, w_ex_bpu_mispredict;
    wire [ROB_PTR_W-1:0] w_ex_bpu_rob;
    wire [5:0]  w_ex_bpu_preg;
    wire [31:0] w_ex_bpu_res, w_ex_bpu_correct_pc;
    wire        w_ex_agu_valid, w_ex_agu_data_valid;
    wire [LSQ_PTR_W-1:0] w_ex_agu_lsq_idx;
    wire [31:0] w_ex_agu_addr, w_ex_agu_store_data;
    wire        w_ex_mul_valid;
    wire [ROB_PTR_W-1:0] w_ex_mul_rob;
    wire [5:0]  w_ex_mul_preg;
    wire [31:0] w_ex_mul_res;

    // ================================================================
    // EX/WB BUFFER -> CDB WIRES
    // ================================================================
    wire        w_wb_alu0_valid, w_wb_alu1_valid, w_wb_alu2_valid, w_wb_alu3_valid;
    wire [ROB_PTR_W-1:0] w_wb_alu0_rob, w_wb_alu1_rob, w_wb_alu2_rob, w_wb_alu3_rob;
    wire [5:0]  w_wb_alu0_preg, w_wb_alu1_preg, w_wb_alu2_preg, w_wb_alu3_preg;
    wire [31:0] w_wb_alu0_res, w_wb_alu1_res, w_wb_alu2_res, w_wb_alu3_res;
    wire        w_wb_bpu_valid, w_wb_bpu_mispredict;
    wire [ROB_PTR_W-1:0] w_wb_bpu_rob;
    wire [5:0]  w_wb_bpu_preg;
    wire [31:0] w_wb_bpu_res, w_wb_bpu_correct_pc;
    wire        w_wb_mul_valid;
    wire [ROB_PTR_W-1:0] w_wb_mul_rob;
    wire [5:0]  w_wb_mul_preg;
    wire [31:0] w_wb_mul_res;

    // ================================================================
    // FETCH POP LOGIC
    // ================================================================
    wire w_queue_pop = !w_queue_empty;

    // ================================================================
    // INSTANCE 1: FETCH STAGE
    // ================================================================
    fetch_stage_top u_fetch (
        .clk            (clk),
        .rst            (rst),
        .enable_pc      (1'b1),
        .queue_pop      (w_queue_pop),
        .stall_in       (w_decode_stall),

        .flush          (w_flush),
        .redirect_valid (w_flush),
        .redirect_pc    (w_flush_correct_pc),

        .pc_current     (dbg_pc_current),
        .pc_iq_out      (w_fetch_pc_iq),
        .inst0          (w_fetch_inst0),
        .inst1          (w_fetch_inst1),
        .inst2          (w_fetch_inst2),
        .inst3          (w_fetch_inst3),
        .valid_inst     (w_fetch_valid),
        .queue_full     (w_queue_full),
        .queue_empty    (w_queue_empty)
    );

    // ================================================================
    // INSTANCE 2: IF/ID PIPELINE BUFFER
    // ================================================================
    if_id_buffer u_ifid (
        .clk        (clk),
        .rst        (rst),
        .flush      (w_flush),
        .stall      (w_decode_stall),

        .pc_in      (w_fetch_pc_iq),
        .inst0_in   (w_fetch_inst0),
        .inst1_in   (w_fetch_inst1),
        .inst2_in   (w_fetch_inst2),
        .inst3_in   (w_fetch_inst3),
        .valid_in   (w_fetch_valid),

        .pc0_out    (w_ifid_pc0),
        .pc1_out    (w_ifid_pc1),
        .pc2_out    (w_ifid_pc2),
        .pc3_out    (w_ifid_pc3),
        .inst0_out  (w_ifid_inst0),
        .inst1_out  (w_ifid_inst1),
        .inst2_out  (w_ifid_inst2),
        .inst3_out  (w_ifid_inst3),
        .valid_out  (w_ifid_valid)
    );

    // ================================================================
    // INSTANCE 3: DECODE + RENAME + FREELIST + RAT
    // ================================================================
    Decode_Top u_decode (
        .clk                (clk),
        .rst                (rst),

        // From IF/ID buffer
        .ins0_in            (w_ifid_inst0),
        .ins1_in            (w_ifid_inst1),
        .ins2_in            (w_ifid_inst2),
        .ins3_in            (w_ifid_inst3),
        .fetch_valid        (w_ifid_valid),

        // From commit stage (4-wide)
        .dealloc_en         (w_commit_free_valid),
        .old_phys_reg_commit(w_commit_old_phys_rd),
        .rd_valid_at_commit (w_commit_free_valid),

        // From ROB commit (RRAT)
        .commit_valid       (w_commit_valid),
        .commit_arch_rd     (w_commit_arch_rd),
        .commit_phys_rd     (w_commit_phys_rd),
        .commit_rd_valid    (w_commit_rd_valid),

        // From ROB flush
        .flush              (w_flush),
        .flush_free_valid   (w_flush_free_valid),
        .flush_free_phys_rd (w_flush_free_phys_rd),

        // Downstream capacity (lsq_full piggybacked onto iq_full)
        .rob_full           (w_rob_full),
        .iq_full            (w_iq_full || w_lsq_full),

        // Decoded fields
        .ins0_rs1(w_ins0_rs1), .ins0_rs2(w_ins0_rs2), .ins0_rd(w_ins0_rd),
        .ins0_imm(w_ins0_imm), .ins0_opcode(w_ins0_opcode),
        .ins0_funct3(w_ins0_funct3), .ins0_funct7(w_ins0_funct7),
        .ins0_is_alu(w_ins0_is_alu), .ins0_is_mul(w_ins0_is_mul), .ins0_is_load(w_ins0_is_load), .ins0_is_store(w_ins0_is_store),
        .ins0_is_branch(w_ins0_is_branch), .ins0_is_jal(w_ins0_is_jal), .ins0_is_jalr(w_ins0_is_jalr),
        .ins0_is_lui(w_ins0_is_lui), .ins0_is_auipc(w_ins0_is_auipc),

        .ins1_rs1(w_ins1_rs1), .ins1_rs2(w_ins1_rs2), .ins1_rd(w_ins1_rd),
        .ins1_imm(w_ins1_imm), .ins1_opcode(w_ins1_opcode),
        .ins1_funct3(w_ins1_funct3), .ins1_funct7(w_ins1_funct7),
        .ins1_is_alu(w_ins1_is_alu), .ins1_is_mul(w_ins1_is_mul), .ins1_is_load(w_ins1_is_load), .ins1_is_store(w_ins1_is_store),
        .ins1_is_branch(w_ins1_is_branch), .ins1_is_jal(w_ins1_is_jal), .ins1_is_jalr(w_ins1_is_jalr),
        .ins1_is_lui(w_ins1_is_lui), .ins1_is_auipc(w_ins1_is_auipc),

        .ins2_rs1(w_ins2_rs1), .ins2_rs2(w_ins2_rs2), .ins2_rd(w_ins2_rd),
        .ins2_imm(w_ins2_imm), .ins2_opcode(w_ins2_opcode),
        .ins2_funct3(w_ins2_funct3), .ins2_funct7(w_ins2_funct7),
        .ins2_is_alu(w_ins2_is_alu), .ins2_is_mul(w_ins2_is_mul), .ins2_is_load(w_ins2_is_load), .ins2_is_store(w_ins2_is_store),
        .ins2_is_branch(w_ins2_is_branch), .ins2_is_jal(w_ins2_is_jal), .ins2_is_jalr(w_ins2_is_jalr),
        .ins2_is_lui(w_ins2_is_lui), .ins2_is_auipc(w_ins2_is_auipc),

        .ins3_rs1(w_ins3_rs1), .ins3_rs2(w_ins3_rs2), .ins3_rd(w_ins3_rd),
        .ins3_imm(w_ins3_imm), .ins3_opcode(w_ins3_opcode),
        .ins3_funct3(w_ins3_funct3), .ins3_funct7(w_ins3_funct7),
        .ins3_is_alu(w_ins3_is_alu), .ins3_is_mul(w_ins3_is_mul), .ins3_is_load(w_ins3_is_load), .ins3_is_store(w_ins3_is_store),
        .ins3_is_branch(w_ins3_is_branch), .ins3_is_jal(w_ins3_is_jal), .ins3_is_jalr(w_ins3_is_jalr),
        .ins3_is_lui(w_ins3_is_lui), .ins3_is_auipc(w_ins3_is_auipc),

        // Renamed registers
        .phys_rs1_out           (w_phys_rs1),
        .phys_rs2_out           (w_phys_rs2),
        .phys_rd_out            (w_phys_rd),
        .old_phys_reg_out       (w_old_phys_reg),

        // Validity / control
        .rd_valid_out           (w_rd_valid),
        .rs1_valid_out          (w_rs1_valid),
        .rs2_valid_out          (w_rs2_valid),
        .rd_valid_at_rename_out (w_rd_valid_at_rename),
        .valid_out              (w_dec_valid),
        .stall_out              (w_decode_stall),

        // PC passthrough
        .pc0_in(w_ifid_pc0), .pc1_in(w_ifid_pc1),
        .pc2_in(w_ifid_pc2), .pc3_in(w_ifid_pc3),
        .pc0_out(w_dec_pc0), .pc1_out(w_dec_pc1),
        .pc2_out(w_dec_pc2), .pc3_out(w_dec_pc3),

        // Debug
        .freelist_bitmap_debug  (dbg_freelist_bitmap),
        .rat_debug              (dbg_rat)
    );

    // ================================================================
    // INSTANCE 4: ID/IQ PIPELINE BUFFER
    // ================================================================
    id_iq_buffer u_id_iq (
        .clk            (clk),
        .rst            (rst),
        .flush          (w_flush),
        .stall          (w_backend_stall),

        // From Decode_Top
        .ins0_opcode(w_ins0_opcode), .ins1_opcode(w_ins1_opcode),
        .ins2_opcode(w_ins2_opcode), .ins3_opcode(w_ins3_opcode),
        .ins0_funct3(w_ins0_funct3), .ins1_funct3(w_ins1_funct3),
        .ins2_funct3(w_ins2_funct3), .ins3_funct3(w_ins3_funct3),
        .ins0_funct7(w_ins0_funct7), .ins1_funct7(w_ins1_funct7),
        .ins2_funct7(w_ins2_funct7), .ins3_funct7(w_ins3_funct7),
        .ins0_imm(w_ins0_imm), .ins1_imm(w_ins1_imm),
        .ins2_imm(w_ins2_imm), .ins3_imm(w_ins3_imm),
        .ins0_rd(w_ins0_rd), .ins1_rd(w_ins1_rd),
        .ins2_rd(w_ins2_rd), .ins3_rd(w_ins3_rd),

        .ins0_is_alu(w_ins0_is_alu), .ins1_is_alu(w_ins1_is_alu),
        .ins2_is_alu(w_ins2_is_alu), .ins3_is_alu(w_ins3_is_alu),
        .ins0_is_mul(w_ins0_is_mul), .ins1_is_mul(w_ins1_is_mul),
        .ins2_is_mul(w_ins2_is_mul), .ins3_is_mul(w_ins3_is_mul),
        .ins0_is_load(w_ins0_is_load), .ins1_is_load(w_ins1_is_load),
        .ins2_is_load(w_ins2_is_load), .ins3_is_load(w_ins3_is_load),
        .ins0_is_store(w_ins0_is_store), .ins1_is_store(w_ins1_is_store),
        .ins2_is_store(w_ins2_is_store), .ins3_is_store(w_ins3_is_store),
        .ins0_is_branch(w_ins0_is_branch), .ins1_is_branch(w_ins1_is_branch),
        .ins2_is_branch(w_ins2_is_branch), .ins3_is_branch(w_ins3_is_branch),
        .ins0_is_jal(w_ins0_is_jal), .ins1_is_jal(w_ins1_is_jal),
        .ins2_is_jal(w_ins2_is_jal), .ins3_is_jal(w_ins3_is_jal),
        .ins0_is_jalr(w_ins0_is_jalr), .ins1_is_jalr(w_ins1_is_jalr),
        .ins2_is_jalr(w_ins2_is_jalr), .ins3_is_jalr(w_ins3_is_jalr),
        .ins0_is_lui(w_ins0_is_lui), .ins1_is_lui(w_ins1_is_lui),
        .ins2_is_lui(w_ins2_is_lui), .ins3_is_lui(w_ins3_is_lui),
        .ins0_is_auipc(w_ins0_is_auipc), .ins1_is_auipc(w_ins1_is_auipc),
        .ins2_is_auipc(w_ins2_is_auipc), .ins3_is_auipc(w_ins3_is_auipc),

        .phys_rs1_in            (w_phys_rs1),
        .phys_rs2_in            (w_phys_rs2),
        .phys_rd_in             (w_phys_rd),
        .old_phys_reg_in        (w_old_phys_reg),
        .rd_valid_in            (w_rd_valid),
        .rs1_valid_in           (w_rs1_valid),
        .rs2_valid_in           (w_rs2_valid),
        .rd_valid_at_rename_in  (w_rd_valid_at_rename),
        .valid_in               (w_decode_stall ? 4'b0 : w_dec_valid),

        .pc0_in(w_dec_pc0), .pc1_in(w_dec_pc1),
        .pc2_in(w_dec_pc2), .pc3_in(w_dec_pc3),

        // To Issue Top
        .dispatch_valid         (w_disp_valid),
        .dispatch_is_alu        (w_disp_is_alu),
        .dispatch_is_mul        (w_disp_is_mul),
        .dispatch_is_load       (w_disp_is_load),
        .dispatch_is_store      (w_disp_is_store),
        .dispatch_is_branch     (w_disp_is_branch),
        .dispatch_is_jal        (w_disp_is_jal),
        .dispatch_is_jalr       (w_disp_is_jalr),
        .dispatch_is_lui        (w_disp_is_lui),
        .dispatch_is_auipc      (w_disp_is_auipc),
        .dispatch_phys_rs1      (w_disp_phys_rs1),
        .dispatch_phys_rs2      (w_disp_phys_rs2),
        .dispatch_phys_rd       (w_disp_phys_rd),
        .dispatch_old_phys_rd   (w_disp_old_phys_rd),
        .dispatch_arch_rd       (w_disp_arch_rd),
        .dispatch_rd_valid      (w_disp_rd_valid),
        .dispatch_rs1_valid     (w_disp_rs1_valid),
        .dispatch_rs2_valid     (w_disp_rs2_valid),
        .dispatch_opcode        (w_disp_opcode),
        .dispatch_funct3        (w_disp_funct3),
        .dispatch_funct7        (w_disp_funct7),
        .dispatch_imm           (w_disp_imm),
        .dispatch_pc0           (w_disp_pc0),
        .dispatch_pc1           (w_disp_pc1),
        .dispatch_pc2           (w_disp_pc2),
        .dispatch_pc3           (w_disp_pc3),
        .dispatch_rd_valid_at_rename (w_disp_rd_valid_at_rename)
    );

    // ================================================================
    // INSTANCE 5: ISSUE STAGE (ROB + IQ + LSQ + PRF + ARF + MEM)
    // ================================================================
    issue_top #(
        .ROB_DEPTH (ROB_DEPTH),
        .ROB_PTR_W (ROB_PTR_W),
        .LSQ_DEPTH (LSQ_DEPTH),
        .LSQ_PTR_W (LSQ_PTR_W),
        .AQ_DEPTH  (AQ_DEPTH),
        .AQ_PTR_W  (AQ_PTR_W),
        .MEM_DEPTH (MEM_DEPTH),
        .INIT_FILE (INIT_FILE)
    ) u_issue (
        .clk                (clk),
        .rst                (rst),

        // Dispatch from ID/IQ buffer
        .dispatch_valid     (w_disp_valid),
        .dispatch_is_alu    (w_disp_is_alu),
        .dispatch_is_mul    (w_disp_is_mul),
        .dispatch_is_load   (w_disp_is_load),
        .dispatch_is_store  (w_disp_is_store),
        .dispatch_is_branch (w_disp_is_branch),
        .dispatch_is_jal    (w_disp_is_jal),
        .dispatch_is_jalr   (w_disp_is_jalr),
        .dispatch_is_lui    (w_disp_is_lui),
        .dispatch_is_auipc  (w_disp_is_auipc),
        .dispatch_phys_rs1  (w_disp_phys_rs1),
        .dispatch_phys_rs2  (w_disp_phys_rs2),
        .dispatch_phys_rd   (w_disp_phys_rd),
        .dispatch_old_phys_rd(w_disp_old_phys_rd),
        .dispatch_arch_rd   (w_disp_arch_rd),
        .dispatch_rd_valid  (w_disp_rd_valid),
        .dispatch_rs1_valid (w_disp_rs1_valid),
        .dispatch_rs2_valid (w_disp_rs2_valid),
        .dispatch_opcode    (w_disp_opcode),
        .dispatch_funct3    (w_disp_funct3),
        .dispatch_funct7    (w_disp_funct7),
        .dispatch_imm       (w_disp_imm),
        .dispatch_pc0       (w_disp_pc0),
        .dispatch_pc1       (w_disp_pc1),
        .dispatch_pc2       (w_disp_pc2),
        .dispatch_pc3       (w_disp_pc3),

        // CDB from execute
        .cdb_fu0_valid(cdb_fu0_valid), .cdb_fu0_rob_idx(cdb_fu0_rob_idx),
        .cdb_fu0_phys_reg(cdb_fu0_phys_reg), .cdb_fu0_result(cdb_fu0_result),
        .cdb_fu1_valid(cdb_fu1_valid), .cdb_fu1_rob_idx(cdb_fu1_rob_idx),
        .cdb_fu1_phys_reg(cdb_fu1_phys_reg), .cdb_fu1_result(cdb_fu1_result),
        .cdb_fu2_valid(cdb_fu2_valid), .cdb_fu2_rob_idx(cdb_fu2_rob_idx),
        .cdb_fu2_phys_reg(cdb_fu2_phys_reg), .cdb_fu2_result(cdb_fu2_result),
        .cdb_fu3_valid(cdb_fu3_valid), .cdb_fu3_rob_idx(cdb_fu3_rob_idx),
        .cdb_fu3_phys_reg(cdb_fu3_phys_reg), .cdb_fu3_result(cdb_fu3_result),
        .cdb_bpu_valid(cdb_bpu_valid), .cdb_bpu_rob_idx(cdb_bpu_rob_idx),
        .cdb_bpu_phys_reg(cdb_bpu_phys_reg), .cdb_bpu_result(cdb_bpu_result),
        .cdb_bpu_mispredict(cdb_bpu_mispredict), .cdb_bpu_correct_pc(cdb_bpu_correct_pc),
        .cdb_mul_valid(cdb_mul_valid), .cdb_mul_rob_idx(cdb_mul_rob_idx),
        .cdb_mul_phys_reg(cdb_mul_phys_reg), .cdb_mul_result(cdb_mul_result),

        // AGU writeback
        .agu_wb_valid(agu_wb_valid), .agu_wb_lsq_idx(agu_wb_lsq_idx),
        .agu_wb_addr(agu_wb_addr), .agu_wb_store_data(agu_wb_store_data),
        .agu_wb_data_valid(agu_wb_data_valid),

        // Buffer controls
        .aq_buf_accept(aq_buf_accept), .agu_ready(agu_ready),
        .fu0_ready(fu0_ready), .fu1_ready(fu1_ready),
        .fu2_ready(fu2_ready), .fu3_ready(fu3_ready),
        .bpu_ready(bpu_ready),
        .mul_ready(mul_ready),

        // Back-pressure
        .rob_full(w_rob_full), .iq_full(w_iq_full), .lsq_full(w_lsq_full),

        // Issue outputs -> execute
        .bpu_valid(bpu_valid), .bpu_seq_num(bpu_seq_num), .bpu_opcode(bpu_opcode),
        .bpu_funct3(bpu_funct3), .bpu_imm(bpu_imm),
        .bpu_phys_rs1(bpu_phys_rs1), .bpu_phys_rs2(bpu_phys_rs2), .bpu_phys_rd(bpu_phys_rd),
        .bpu_rs1_val(bpu_rs1_val), .bpu_rs2_val(bpu_rs2_val), .bpu_pc(bpu_pc),

        .fu0_valid(fu0_valid), .fu0_seq_num(fu0_seq_num), .fu0_opcode(fu0_opcode),
        .fu0_funct3(fu0_funct3), .fu0_funct7(fu0_funct7), .fu0_imm(fu0_imm),
        .fu0_phys_rs1(fu0_phys_rs1), .fu0_phys_rs2(fu0_phys_rs2), .fu0_phys_rd(fu0_phys_rd),
        .fu0_rs1_val(fu0_rs1_val), .fu0_rs2_val(fu0_rs2_val), .fu0_pc(fu0_pc),

        .fu1_valid(fu1_valid), .fu1_seq_num(fu1_seq_num), .fu1_opcode(fu1_opcode),
        .fu1_funct3(fu1_funct3), .fu1_funct7(fu1_funct7), .fu1_imm(fu1_imm),
        .fu1_phys_rs1(fu1_phys_rs1), .fu1_phys_rs2(fu1_phys_rs2), .fu1_phys_rd(fu1_phys_rd),
        .fu1_rs1_val(fu1_rs1_val), .fu1_rs2_val(fu1_rs2_val), .fu1_pc(fu1_pc),

        .fu2_valid(fu2_valid), .fu2_seq_num(fu2_seq_num), .fu2_opcode(fu2_opcode),
        .fu2_funct3(fu2_funct3), .fu2_funct7(fu2_funct7), .fu2_imm(fu2_imm),
        .fu2_phys_rs1(fu2_phys_rs1), .fu2_phys_rs2(fu2_phys_rs2), .fu2_phys_rd(fu2_phys_rd),
        .fu2_rs1_val(fu2_rs1_val), .fu2_rs2_val(fu2_rs2_val), .fu2_pc(fu2_pc),

        .fu3_valid(fu3_valid), .fu3_seq_num(fu3_seq_num), .fu3_opcode(fu3_opcode),
        .fu3_funct3(fu3_funct3), .fu3_funct7(fu3_funct7), .fu3_imm(fu3_imm),
        .fu3_phys_rs1(fu3_phys_rs1), .fu3_phys_rs2(fu3_phys_rs2), .fu3_phys_rd(fu3_phys_rd),
        .fu3_rs1_val(fu3_rs1_val), .fu3_rs2_val(fu3_rs2_val), .fu3_pc(fu3_pc),

        .mul_valid(mul_valid), .mul_seq_num(mul_seq_num),
        .mul_funct3(mul_funct3),
        .mul_phys_rs1(mul_phys_rs1), .mul_phys_rs2(mul_phys_rs2), .mul_phys_rd(mul_phys_rd),
        .mul_rs1_val(mul_rs1_val), .mul_rs2_val(mul_rs2_val),

        .agu_valid(agu_valid), .agu_seq_num(agu_seq_num), .agu_opcode(agu_opcode),
        .agu_funct3(agu_funct3), .agu_imm(agu_imm),
        .agu_phys_rs1(agu_phys_rs1), .agu_phys_rs2(agu_phys_rs2), .agu_phys_rd(agu_phys_rd),
        .agu_is_load(agu_is_load), .agu_is_store(agu_is_store),

        .aq_valid(aq_valid), .aq_lsq_idx(aq_lsq_idx),
        .aq_rs1_val(aq_rs1_val), .aq_rs2_val(aq_rs2_val),
        .aq_imm_out(aq_imm_out), .aq_funct3_out(aq_funct3_out),
        .aq_is_load_out(aq_is_load_out), .aq_is_store_out(aq_is_store_out),
        .aq_rs2_ready(aq_rs2_ready),

        // Flush
        .flush(w_flush), .flush_seq_num(w_flush_seq_num),
        .flush_correct_pc(w_flush_correct_pc),

        // Commit -> Freelist
        .commit_free_valid(w_commit_free_valid), .commit_old_phys_rd(w_commit_old_phys_rd),
        .flush_free_valid(w_flush_free_valid), .flush_free_phys_rd(w_flush_free_phys_rd),

        // Commit -> RRAT
        .commit_valid(w_commit_valid), .commit_arch_rd(w_commit_arch_rd),
        .commit_phys_rd(w_commit_phys_rd), .commit_result(w_commit_result),
        .commit_rd_valid(w_commit_rd_valid),

        // Shadow RAT
        .arch_to_phys_flush(w_arch_to_phys_flush),

        // Debug
        .dbg_rob_head(dbg_rob_head), .dbg_rob_tail(dbg_rob_tail), .dbg_rob_count(dbg_rob_count),
        .dbg_lsq_head(dbg_lsq_head), .dbg_lsq_tail(dbg_lsq_tail), .dbg_lsq_count(dbg_lsq_count),
        .dbg_arf_regfile(dbg_arf_regfile), .dbg_arf_rat(dbg_arf_rat),
        .dbg_rd_addr0(dbg_rd_addr0), .dbg_rd_data0(dbg_rd_data0),
        .dbg_rd_addr1(dbg_rd_addr1), .dbg_rd_data1(dbg_rd_data1)
    );

    assign dbg_arch_to_phys_flush = w_arch_to_phys_flush;

    // ================================================================
    // INSTANCE 6: IQ/EX PIPELINE BUFFER
    // ================================================================
    iq_ex_buffer #(.LSQ_PTR_W(LSQ_PTR_W)) u_iq_ex (
        .clk(clk), .rst(rst), .flush(w_flush),
        // FU0
        .fu0_valid_in(fu0_valid), .fu0_seq_num_in(fu0_seq_num),
        .fu0_opcode_in(fu0_opcode), .fu0_funct3_in(fu0_funct3),
        .fu0_funct7_in(fu0_funct7), .fu0_imm_in(fu0_imm),
        .fu0_phys_rd_in(fu0_phys_rd),
        .fu0_rs1_val_in(fu0_rs1_val), .fu0_rs2_val_in(fu0_rs2_val),
        .fu0_pc_in(fu0_pc),
        .fu0_valid_out(w_buf_fu0_valid), .fu0_seq_num_out(w_buf_fu0_seq),
        .fu0_opcode_out(w_buf_fu0_opc), .fu0_funct3_out(w_buf_fu0_f3),
        .fu0_funct7_out(w_buf_fu0_f7), .fu0_imm_out(w_buf_fu0_imm),
        .fu0_phys_rd_out(w_buf_fu0_rd),
        .fu0_rs1_val_out(w_buf_fu0_rs1v), .fu0_rs2_val_out(w_buf_fu0_rs2v),
        .fu0_pc_out(w_buf_fu0_pc),
        // FU1
        .fu1_valid_in(fu1_valid), .fu1_seq_num_in(fu1_seq_num),
        .fu1_opcode_in(fu1_opcode), .fu1_funct3_in(fu1_funct3),
        .fu1_funct7_in(fu1_funct7), .fu1_imm_in(fu1_imm),
        .fu1_phys_rd_in(fu1_phys_rd),
        .fu1_rs1_val_in(fu1_rs1_val), .fu1_rs2_val_in(fu1_rs2_val),
        .fu1_pc_in(fu1_pc),
        .fu1_valid_out(w_buf_fu1_valid), .fu1_seq_num_out(w_buf_fu1_seq),
        .fu1_opcode_out(w_buf_fu1_opc), .fu1_funct3_out(w_buf_fu1_f3),
        .fu1_funct7_out(w_buf_fu1_f7), .fu1_imm_out(w_buf_fu1_imm),
        .fu1_phys_rd_out(w_buf_fu1_rd),
        .fu1_rs1_val_out(w_buf_fu1_rs1v), .fu1_rs2_val_out(w_buf_fu1_rs2v),
        .fu1_pc_out(w_buf_fu1_pc),
        // FU2
        .fu2_valid_in(fu2_valid), .fu2_seq_num_in(fu2_seq_num),
        .fu2_opcode_in(fu2_opcode), .fu2_funct3_in(fu2_funct3),
        .fu2_funct7_in(fu2_funct7), .fu2_imm_in(fu2_imm),
        .fu2_phys_rd_in(fu2_phys_rd),
        .fu2_rs1_val_in(fu2_rs1_val), .fu2_rs2_val_in(fu2_rs2_val),
        .fu2_pc_in(fu2_pc),
        .fu2_valid_out(w_buf_fu2_valid), .fu2_seq_num_out(w_buf_fu2_seq),
        .fu2_opcode_out(w_buf_fu2_opc), .fu2_funct3_out(w_buf_fu2_f3),
        .fu2_funct7_out(w_buf_fu2_f7), .fu2_imm_out(w_buf_fu2_imm),
        .fu2_phys_rd_out(w_buf_fu2_rd),
        .fu2_rs1_val_out(w_buf_fu2_rs1v), .fu2_rs2_val_out(w_buf_fu2_rs2v),
        .fu2_pc_out(w_buf_fu2_pc),
        // FU3
        .fu3_valid_in(fu3_valid), .fu3_seq_num_in(fu3_seq_num),
        .fu3_opcode_in(fu3_opcode), .fu3_funct3_in(fu3_funct3),
        .fu3_funct7_in(fu3_funct7), .fu3_imm_in(fu3_imm),
        .fu3_phys_rd_in(fu3_phys_rd),
        .fu3_rs1_val_in(fu3_rs1_val), .fu3_rs2_val_in(fu3_rs2_val),
        .fu3_pc_in(fu3_pc),
        .fu3_valid_out(w_buf_fu3_valid), .fu3_seq_num_out(w_buf_fu3_seq),
        .fu3_opcode_out(w_buf_fu3_opc), .fu3_funct3_out(w_buf_fu3_f3),
        .fu3_funct7_out(w_buf_fu3_f7), .fu3_imm_out(w_buf_fu3_imm),
        .fu3_phys_rd_out(w_buf_fu3_rd),
        .fu3_rs1_val_out(w_buf_fu3_rs1v), .fu3_rs2_val_out(w_buf_fu3_rs2v),
        .fu3_pc_out(w_buf_fu3_pc),
        // BPU
        .bpu_valid_in(bpu_valid), .bpu_seq_num_in(bpu_seq_num),
        .bpu_opcode_in(bpu_opcode), .bpu_funct3_in(bpu_funct3),
        .bpu_imm_in(bpu_imm), .bpu_phys_rd_in(bpu_phys_rd),
        .bpu_rs1_val_in(bpu_rs1_val), .bpu_rs2_val_in(bpu_rs2_val),
        .bpu_pc_in(bpu_pc),
        .bpu_valid_out(w_buf_bpu_valid), .bpu_seq_num_out(w_buf_bpu_seq),
        .bpu_opcode_out(w_buf_bpu_opc), .bpu_funct3_out(w_buf_bpu_f3),
        .bpu_imm_out(w_buf_bpu_imm), .bpu_phys_rd_out(w_buf_bpu_rd),
        .bpu_rs1_val_out(w_buf_bpu_rs1v), .bpu_rs2_val_out(w_buf_bpu_rs2v),
        .bpu_pc_out(w_buf_bpu_pc),
        // MUL
        .mul_valid_in(mul_valid), .mul_seq_num_in(mul_seq_num),
        .mul_funct3_in(mul_funct3), .mul_phys_rd_in(mul_phys_rd),
        .mul_rs1_val_in(mul_rs1_val), .mul_rs2_val_in(mul_rs2_val),
        .mul_valid_out(w_buf_mul_valid), .mul_seq_num_out(w_buf_mul_seq),
        .mul_funct3_out(w_buf_mul_f3), .mul_phys_rd_out(w_buf_mul_rd),
        .mul_rs1_val_out(w_buf_mul_rs1v), .mul_rs2_val_out(w_buf_mul_rs2v),
        // AGU (from AQ head)
        .agu_valid_in(aq_valid), .agu_lsq_idx_in(aq_lsq_idx),
        .agu_rs1_val_in(aq_rs1_val), .agu_rs2_val_in(aq_rs2_val),
        .agu_imm_in(aq_imm_out), .agu_funct3_in(aq_funct3_out),
        .agu_is_load_in(aq_is_load_out), .agu_is_store_in(aq_is_store_out),
        .agu_rs2_ready_in(aq_rs2_ready), .agu_ready_in(agu_ready),
        .agu_valid_out(w_buf_agu_valid), .agu_lsq_idx_out(w_buf_agu_lsq_idx),
        .agu_rs1_val_out(w_buf_agu_rs1v), .agu_rs2_val_out(w_buf_agu_rs2v),
        .agu_imm_out(w_buf_agu_imm), .agu_funct3_out(w_buf_agu_f3),
        .agu_is_load_out(w_buf_agu_is_load), .agu_is_store_out(w_buf_agu_is_store),
        .agu_rs2_ready_out(w_buf_agu_rs2_ready),
        // AQ pop -> issue_top
        .aq_buf_accept(aq_buf_accept)
    );

    // ================================================================
    // INSTANCE 7: EXECUTE STAGE (4x ALU + BPU + AGU)
    // ================================================================
    Execute_Top #(
        .ROB_PTR_W(ROB_PTR_W),
        .LSQ_PTR_W(LSQ_PTR_W)
    ) u_execute (
        .clk(clk), .rst(rst), .flush(w_flush),
        // FU0
        .fu0_valid_in(w_buf_fu0_valid), .fu0_seq_num(w_buf_fu0_seq),
        .fu0_opcode(w_buf_fu0_opc), .fu0_funct3(w_buf_fu0_f3),
        .fu0_funct7(w_buf_fu0_f7), .fu0_imm(w_buf_fu0_imm),
        .fu0_phys_rd(w_buf_fu0_rd),
        .fu0_rs1_val(w_buf_fu0_rs1v), .fu0_rs2_val(w_buf_fu0_rs2v),
        .fu0_pc(w_buf_fu0_pc),
        // FU1
        .fu1_valid_in(w_buf_fu1_valid), .fu1_seq_num(w_buf_fu1_seq),
        .fu1_opcode(w_buf_fu1_opc), .fu1_funct3(w_buf_fu1_f3),
        .fu1_funct7(w_buf_fu1_f7), .fu1_imm(w_buf_fu1_imm),
        .fu1_phys_rd(w_buf_fu1_rd),
        .fu1_rs1_val(w_buf_fu1_rs1v), .fu1_rs2_val(w_buf_fu1_rs2v),
        .fu1_pc(w_buf_fu1_pc),
        // FU2
        .fu2_valid_in(w_buf_fu2_valid), .fu2_seq_num(w_buf_fu2_seq),
        .fu2_opcode(w_buf_fu2_opc), .fu2_funct3(w_buf_fu2_f3),
        .fu2_funct7(w_buf_fu2_f7), .fu2_imm(w_buf_fu2_imm),
        .fu2_phys_rd(w_buf_fu2_rd),
        .fu2_rs1_val(w_buf_fu2_rs1v), .fu2_rs2_val(w_buf_fu2_rs2v),
        .fu2_pc(w_buf_fu2_pc),
        // FU3
        .fu3_valid_in(w_buf_fu3_valid), .fu3_seq_num(w_buf_fu3_seq),
        .fu3_opcode(w_buf_fu3_opc), .fu3_funct3(w_buf_fu3_f3),
        .fu3_funct7(w_buf_fu3_f7), .fu3_imm(w_buf_fu3_imm),
        .fu3_phys_rd(w_buf_fu3_rd),
        .fu3_rs1_val(w_buf_fu3_rs1v), .fu3_rs2_val(w_buf_fu3_rs2v),
        .fu3_pc(w_buf_fu3_pc),
        // BPU
        .bpu_valid_in(w_buf_bpu_valid), .bpu_seq_num(w_buf_bpu_seq),
        .bpu_opcode(w_buf_bpu_opc), .bpu_funct3(w_buf_bpu_f3),
        .bpu_imm(w_buf_bpu_imm), .bpu_phys_rd(w_buf_bpu_rd),
        .bpu_rs1_val(w_buf_bpu_rs1v), .bpu_rs2_val(w_buf_bpu_rs2v),
        .bpu_pc(w_buf_bpu_pc),
        // AGU
        .agu_valid_in(w_buf_agu_valid), .agu_lsq_idx(w_buf_agu_lsq_idx),
        .agu_rs1_val(w_buf_agu_rs1v), .agu_rs2_val(w_buf_agu_rs2v),
        .agu_imm(w_buf_agu_imm), .agu_funct3(w_buf_agu_f3),
        .agu_is_load(w_buf_agu_is_load), .agu_is_store(w_buf_agu_is_store),
        .agu_rs2_ready(w_buf_agu_rs2_ready),
        // CDB outputs -> ex_wb_buffer (no longer direct to issue_top)
        .alu0_valid_out(w_ex_alu0_valid), .alu0_rob_idx(w_ex_alu0_rob),
        .alu0_phys_reg(w_ex_alu0_preg), .alu0_result(w_ex_alu0_res),
        .alu1_valid_out(w_ex_alu1_valid), .alu1_rob_idx(w_ex_alu1_rob),
        .alu1_phys_reg(w_ex_alu1_preg), .alu1_result(w_ex_alu1_res),
        .alu2_valid_out(w_ex_alu2_valid), .alu2_rob_idx(w_ex_alu2_rob),
        .alu2_phys_reg(w_ex_alu2_preg), .alu2_result(w_ex_alu2_res),
        .alu3_valid_out(w_ex_alu3_valid), .alu3_rob_idx(w_ex_alu3_rob),
        .alu3_phys_reg(w_ex_alu3_preg), .alu3_result(w_ex_alu3_res),
        .bpu_valid_out(w_ex_bpu_valid), .bpu_rob_idx(w_ex_bpu_rob),
        .bpu_phys_reg(w_ex_bpu_preg), .bpu_result(w_ex_bpu_res),
        .bpu_mispredict(w_ex_bpu_mispredict), .bpu_correct_pc(w_ex_bpu_correct_pc),
        // AGU writeback -> ex_wb_buffer (bypasses CDB)
        .agu_wb_valid(w_ex_agu_valid), .agu_wb_lsq_idx(w_ex_agu_lsq_idx),
        .agu_wb_addr(w_ex_agu_addr), .agu_wb_store_data(w_ex_agu_store_data),
        .agu_wb_data_valid(w_ex_agu_data_valid),
        // Ready signals -> issue_top + iq_ex_buffer
        .fu0_ready(fu0_ready), .fu1_ready(fu1_ready),
        .fu2_ready(fu2_ready), .fu3_ready(fu3_ready),
        .bpu_ready(bpu_ready), .agu_ready(agu_ready),
        .mul_ready(mul_ready),
        // MUL
        .mul_valid_in(w_buf_mul_valid), .mul_seq_num(w_buf_mul_seq),
        .mul_funct3(w_buf_mul_f3), .mul_phys_rd(w_buf_mul_rd),
        .mul_rs1_val(w_buf_mul_rs1v), .mul_rs2_val(w_buf_mul_rs2v),
        .mul_valid_out(w_ex_mul_valid), .mul_rob_idx(w_ex_mul_rob),
        .mul_phys_reg(w_ex_mul_preg), .mul_result(w_ex_mul_res)
    );

    // ================================================================
    // INSTANCE 8: EX/WB PIPELINE BUFFER
    // ================================================================
    ex_wb_buffer #(
        .ROB_PTR_W(ROB_PTR_W),
        .LSQ_PTR_W(LSQ_PTR_W)
    ) u_ex_wb (
        .clk(clk), .rst(rst), .flush(w_flush),
        // ALU0
        .alu0_valid_in(w_ex_alu0_valid), .alu0_rob_idx_in(w_ex_alu0_rob),
        .alu0_phys_reg_in(w_ex_alu0_preg), .alu0_result_in(w_ex_alu0_res),
        .alu0_valid_out(w_wb_alu0_valid), .alu0_rob_idx_out(w_wb_alu0_rob),
        .alu0_phys_reg_out(w_wb_alu0_preg), .alu0_result_out(w_wb_alu0_res),
        // ALU1
        .alu1_valid_in(w_ex_alu1_valid), .alu1_rob_idx_in(w_ex_alu1_rob),
        .alu1_phys_reg_in(w_ex_alu1_preg), .alu1_result_in(w_ex_alu1_res),
        .alu1_valid_out(w_wb_alu1_valid), .alu1_rob_idx_out(w_wb_alu1_rob),
        .alu1_phys_reg_out(w_wb_alu1_preg), .alu1_result_out(w_wb_alu1_res),
        // ALU2
        .alu2_valid_in(w_ex_alu2_valid), .alu2_rob_idx_in(w_ex_alu2_rob),
        .alu2_phys_reg_in(w_ex_alu2_preg), .alu2_result_in(w_ex_alu2_res),
        .alu2_valid_out(w_wb_alu2_valid), .alu2_rob_idx_out(w_wb_alu2_rob),
        .alu2_phys_reg_out(w_wb_alu2_preg), .alu2_result_out(w_wb_alu2_res),
        // ALU3
        .alu3_valid_in(w_ex_alu3_valid), .alu3_rob_idx_in(w_ex_alu3_rob),
        .alu3_phys_reg_in(w_ex_alu3_preg), .alu3_result_in(w_ex_alu3_res),
        .alu3_valid_out(w_wb_alu3_valid), .alu3_rob_idx_out(w_wb_alu3_rob),
        .alu3_phys_reg_out(w_wb_alu3_preg), .alu3_result_out(w_wb_alu3_res),
        // BPU
        .bpu_valid_in(w_ex_bpu_valid), .bpu_rob_idx_in(w_ex_bpu_rob),
        .bpu_phys_reg_in(w_ex_bpu_preg), .bpu_result_in(w_ex_bpu_res),
        .bpu_mispredict_in(w_ex_bpu_mispredict), .bpu_correct_pc_in(w_ex_bpu_correct_pc),
        .bpu_valid_out(w_wb_bpu_valid), .bpu_rob_idx_out(w_wb_bpu_rob),
        .bpu_phys_reg_out(w_wb_bpu_preg), .bpu_result_out(w_wb_bpu_res),
        .bpu_mispredict_out(w_wb_bpu_mispredict), .bpu_correct_pc_out(w_wb_bpu_correct_pc),
        // MUL
        .mul_valid_in(w_ex_mul_valid), .mul_rob_idx_in(w_ex_mul_rob),
        .mul_phys_reg_in(w_ex_mul_preg), .mul_result_in(w_ex_mul_res),
        .mul_valid_out(w_wb_mul_valid), .mul_rob_idx_out(w_wb_mul_rob),
        .mul_phys_reg_out(w_wb_mul_preg), .mul_result_out(w_wb_mul_res),
        // AGU (bypasses CDB, goes directly to issue_top LSQ)
        .agu_valid_in(w_ex_agu_valid), .agu_lsq_idx_in(w_ex_agu_lsq_idx),
        .agu_addr_in(w_ex_agu_addr), .agu_store_data_in(w_ex_agu_store_data),
        .agu_data_valid_in(w_ex_agu_data_valid),
        .agu_valid_out(agu_wb_valid), .agu_lsq_idx_out(agu_wb_lsq_idx),
        .agu_addr_out(agu_wb_addr), .agu_store_data_out(agu_wb_store_data),
        .agu_data_valid_out(agu_wb_data_valid)
    );

    // ================================================================
    // INSTANCE 9: CDB (Common Data Bus)
    // ================================================================
    CDB #(.ROB_PTR_W(ROB_PTR_W)) u_cdb (
        // From ex_wb_buffer
        .alu0_valid(w_wb_alu0_valid), .alu0_rob_idx(w_wb_alu0_rob),
        .alu0_phys_reg(w_wb_alu0_preg), .alu0_result(w_wb_alu0_res),
        .alu1_valid(w_wb_alu1_valid), .alu1_rob_idx(w_wb_alu1_rob),
        .alu1_phys_reg(w_wb_alu1_preg), .alu1_result(w_wb_alu1_res),
        .alu2_valid(w_wb_alu2_valid), .alu2_rob_idx(w_wb_alu2_rob),
        .alu2_phys_reg(w_wb_alu2_preg), .alu2_result(w_wb_alu2_res),
        .alu3_valid(w_wb_alu3_valid), .alu3_rob_idx(w_wb_alu3_rob),
        .alu3_phys_reg(w_wb_alu3_preg), .alu3_result(w_wb_alu3_res),
        .bpu_valid(w_wb_bpu_valid), .bpu_rob_idx(w_wb_bpu_rob),
        .bpu_phys_reg(w_wb_bpu_preg), .bpu_result(w_wb_bpu_res),
        .bpu_mispredict(w_wb_bpu_mispredict), .bpu_correct_pc(w_wb_bpu_correct_pc),
        // LSQ CDB is internal to issue_top, tie off here
        .lsq_valid(1'b0), .lsq_tag(8'd0),
        .lsq_phys_reg(6'd0), .lsq_result(32'd0),
        // MUL
        .mul_valid(w_wb_mul_valid), .mul_rob_idx(w_wb_mul_rob),
        .mul_phys_reg(w_wb_mul_preg), .mul_result(w_wb_mul_res),
        // CDB outputs -> output ports (loop back to issue_top)
        .cdb_fu0_valid(cdb_fu0_valid), .cdb_fu0_rob_idx(cdb_fu0_rob_idx),
        .cdb_fu0_phys_reg(cdb_fu0_phys_reg), .cdb_fu0_result(cdb_fu0_result),
        .cdb_fu1_valid(cdb_fu1_valid), .cdb_fu1_rob_idx(cdb_fu1_rob_idx),
        .cdb_fu1_phys_reg(cdb_fu1_phys_reg), .cdb_fu1_result(cdb_fu1_result),
        .cdb_fu2_valid(cdb_fu2_valid), .cdb_fu2_rob_idx(cdb_fu2_rob_idx),
        .cdb_fu2_phys_reg(cdb_fu2_phys_reg), .cdb_fu2_result(cdb_fu2_result),
        .cdb_fu3_valid(cdb_fu3_valid), .cdb_fu3_rob_idx(cdb_fu3_rob_idx),
        .cdb_fu3_phys_reg(cdb_fu3_phys_reg), .cdb_fu3_result(cdb_fu3_result),
        .cdb_bpu_valid(cdb_bpu_valid), .cdb_bpu_rob_idx(cdb_bpu_rob_idx),
        .cdb_bpu_phys_reg(cdb_bpu_phys_reg), .cdb_bpu_result(cdb_bpu_result),
        .cdb_bpu_mispredict(cdb_bpu_mispredict), .cdb_bpu_correct_pc(cdb_bpu_correct_pc),
        .cdb_lsq_valid(), .cdb_lsq_rob_idx(),
        .cdb_lsq_phys_reg(), .cdb_lsq_result(),
        .cdb_mul_valid(cdb_mul_valid), .cdb_mul_rob_idx(cdb_mul_rob_idx),
        .cdb_mul_phys_reg(cdb_mul_phys_reg), .cdb_mul_result(cdb_mul_result)
    );

endmodule

